### ISSUE TITLE
Fonts and broken URL's and Links

### ISSUE THREAD

**Issue by AlexanderTahtadjian** [AlexanderTahtadjian/fastness-fixer#1]
@hellachella
should we keep the number of fonts at three or reduce it to two. Also How do we determine if a link or URL is broken, and how would we go about to fix it

**Comment by hellachella** [comment]
Yep. Any fonts not in use with your CSS must be removed. Check links by clicking on them and making sure they work. You can also use a link checker for larger projects

https://validator.w3.org/checklink

**Comment by AlexanderTahtadjian** [comment]
ok thanks
