### ISSUE TITLE
Snail image and links

### ISSUE THREAD

**Issue by AlexanderTahtadjian** [AlexanderTahtadjian/fastness-fixer#2]
@JessJodoin
I went back and compressed all of the images, but for some reason only one of them is still not showing. Also I'm not exactly sure how to fix the links because I've been looking over the code and haven't found anything wrong with it (as far as I can tell)

**Comment by JessJodoin** [comment]
Line 45 - the image source says snai1.jpg instead of snail.jpg so just change that 1 to an L and it should be good

**Comment by AlexanderTahtadjian** [comment]
thanks
